- .gitignore
- src/CodeGenerator/CodeGeneratorConfig.php
- src/CodeGenerator/CodeGeneratorFacade.php
- src/CodeGenerator/CodeGeneratorFactory.php
- src/CodeGenerator/Domain/Command/AbstractMaker.php
- src/CodeGenerator/Domain/Command/ConfigMaker.php
- src/CodeGenerator/Domain/Command/DependencyProviderMaker.php
- src/CodeGenerator/Domain/Command/FacadeMaker.php
- src/CodeGenerator/Domain/Command/FactoryMaker.php
- src/CodeGenerator/Domain/Command/MakerInterface.php
- src/CodeGenerator/Domain/Command/ModuleMaker.php
- src/CodeGenerator/Domain/Io/CommandArgumentsParser.php
- src/CodeGenerator/Domain/ReadModel/CommandArguments.php
- src/CodeGenerator/Infrastructure/Template/Command/config-maker.txt
- src/CodeGenerator/Infrastructure/Template/Command/dependency-provider-maker.txt
- src/CodeGenerator/Infrastructure/Template/Command/facade-maker.txt
- src/CodeGenerator/Infrastructure/Template/Command/factory-maker.txt
- Decouple the maker templates from the domain. Inject them instead.
I will create a follow-up PR refactoring the `CommandArgumentsParser` in order to achieve what we talked a few days ago about the "1 argument only needed":
> php gacela make:module Gacela/TestModule
> Decouple the "maker templates" from the domain

- .gitignore
- composer.json
- phpunit.xml
- src/CodeGenerator/CodeGeneratorConfig.php
- src/CodeGenerator/CodeGeneratorFactory.php
- src/CodeGenerator/Domain/Command/AbstractMaker.php
- src/CodeGenerator/Domain/Command/ModuleMaker.php
- src/CodeGenerator/Domain/Io/CommandArguments/CommandArgumentsParser.php
- src/CodeGenerator/Domain/Io/CommandArguments/Exception/CommandArgumentsException.php
- src/CodeGenerator/Domain/Io/CommandArgumentsParser.php
- src/CodeGenerator/Domain/ReadModel/CommandArguments.php
- tests/Integration/CodeGenerator/UsingIncorrectConfigurationTest.php
- tests/Integration/CodeGenerator/UsingMakeConfigTest.php
- tests/Integration/CodeGenerator/UsingMakeDependencyProviderTest.php
- tests/Integration/CodeGenerator/UsingMakeFacadeTest.php
- tests/Integration/CodeGenerator/UsingMakeFactoryTest.php
- tests/Integration/CodeGenerator/UsingMakeModuleTest.php
- tests/Integration/CodeGenerator/composer.json
- tests/Integration/Framework/UsingConfig/LocalConfig/Config.php
- tests/Unit/CodeGenerator/Io/CommandArguments/CommandArgumentsParserTest.php
- tests/Unit/CodeGenerator/Io/CommandArgumentsParserTest.php
Read the composer.json autoload psr-4 to get the directory target from the known namespace. 
This way we have to provide only one argument to the maker command. 
For example: `php gacela make:module App/TestModule` 
- Refactor the `CommandArgumentsParser` to find all possible psr-4 combinations and take the better fit. Then perform some logic to discover the desired target directory and namespace based on the given "desired new module namespace".
> Pass only one argument to the "maker command"

- src/Framework/Config.php
- Use `getcwd()` by default as "ApplicationRootDir"
- Improve error message when `config` dir is missing
> Improve some config errors

- src/Framework/Config.php
- tests/Integration/Framework/UsingConfig/IntegrationTest.php
- tests/Integration/Framework/UsingConfig/LocalConfig/Config.php
- tests/Integration/Framework/UsingConfig/config/omit.yml
- tests/Integration/Framework/UsingConfig/config/subfolder/default.php
Read-only `.php` files and don't throw an exception, but read recursively when a folder is found.
> Allow subfolders on config dir

- src/CodeGenerator/Domain/FileContentGenerator.php
- src/CodeGenerator/Infrastructure/Command/MakeFileCommand.php
- src/CodeGenerator/Infrastructure/Command/MakeModuleCommand.php
Before the code generator was using short names by default. But long class names seem to be a bit more readable, so I would prefer to keep the long names by default and give the possibility of generating them short by using the `-s` option.
- Use long names for the classes by default when using the code generator.
> Using long name by default in the generator code commands

- src/Framework/Config.php
- src/Framework/Config/ConfigInit.php
- src/Framework/Config/ConfigReader/EnvConfigReader.php
- src/Framework/Config/ConfigReader/PhpConfigReader.php
- src/Framework/Config/GacelaJsonConfigFactory.php
- src/Framework/Config/GacelaJsonConfigFactoryInterface.php
- src/Framework/Config/PathFinder.php
- src/Framework/Config/PathFinderInterface.php
- tests/Unit/Framework/Config/ConfigReaderTest.php
The current Config class has a lot of responsibilities and it's almost impossible to write isolated tests (unit) for some of its crucial logic. For example, the logic responsible to read different configs by their types.
- Apply extract class refactoring pattern, moving out the logic that initializes the config key-values to another class. 
- `ConfigInit` depends on abstractions like `PathFinderInterface` and `GacelaJsonConfigFactoryInterface` so it can be easily mock in its unit tests.
> Refactor Config: extract ConfigInit logic

- src/CodeGenerator/CodeGeneratorConfig.php
- src/Framework/Config.php
- tests/Integration/Framework/UsingConfigWithoutGacelaJsonFile/IntegrationTest.php
- tests/Integration/Framework/UsingEnvConfig/IntegrationTest.php
- tests/Integration/Framework/UsingMultipleConfig/IntegrationTest.php
- tests/Integration/Framework/UsingPhpConfig/IntegrationTest.php
- tests/Unit/Framework/ConfigTest.php
- `Config::setConfigReaders()` creates a new config instance singleton, so there is no need to call `init()` right after
> Refactoring Config::setConfigReaders()

- .github/workflows/ci.yml
- src/Framework/ClassResolver/ClassInfo.php
There was a bug for PHP 8.0 for anonymous classes, which has a different behavior when using `get_class`
- Add a strategy for CI pipelines for different OS and PHP versions (7.4, 8.0).
- Fix the bug that affects only PHP 8.0 for anonymous classes.
> Fix PHP 8.0 bug for anonymous classes and added a matrix CI

- src/Framework/ClassResolver/GlobalKey.php
- tests/Unit/Framework/ClassResolver/AbstractClassResolverTest.php
- tests/Unit/Framework/ClassResolver/GlobalKeyTest.php
The `GlobalKey::fromClassName()` wasn't working as expected for modules with more than one word. 
- Fix the bug that should unify all keys for the class resolver.
> Fix bug in GlobalKey for Modules with multi names

- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/ClassResolver/GlobalKey.php
- src/Framework/ClassResolver/ResolvableType.php
- tests/Integration/Framework/GlobalServices/AnonymousClassesTest.php
- tests/Unit/Framework/ClassResolver/AbstractClassResolverTest.php
- tests/Unit/Framework/ClassResolver/GlobalKeyTest.php
- tests/Unit/Framework/ClassResolver/ResolvableTypeTest.php
Currently, you have to pass the resolvable type as the second argument when using `addAnonymousGlobal()`. This shouldn't be necessary if it could be inferred from the parent class of the anonymous class that it's been passed.
- Removed the second argument `string $type` from `addAnonymousGlobal()`
- Infer the parent class from the `object $resolvedClass`
- Separate some logic from `GlobalKey` into a new value object: `ResolvableType`
> Infer the resolvedClass type when using addAnonymousGlobal()

- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/Container/Locator.php
- tests/Unit/Framework/Container/LocatorTest.php
Improves the type annotation in `AbstractClassResolver` and `Locator` to have better psalm support. Additionally the method `Locator::newInstance` will now return `null` instead of a string if the class doesn't exists.
- Added type annotation in `AbstractClassResolver`
- Added type annotation in `Locator`
- `Locator::newInstance` returns `null` if the class doesn't exist.
> Improved type annotation in AbstractClassResolver and Locator

- .github/CONTRIBUTING.md
- .php-cs-fixer.dist.php
- composer.json
Add `->setRiskyAllowed(true)` to `.php-cs-fixer.dist.php` file, 
so, we can drop now the `--allow-risky=yes` from composer.json 😄
> Set Risky Allowed in php-cs-fixer file

- .github/workflows/ci.yml
- Add composer cache on GitHub CI.
- Add PHP 8.1 to the `matrix.php` when running the tests.
> Ensure that Gacela is compatible with PHP 8.1

- phpbench.json
- tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php
- tests/Benchmark/Framework/ClassResolver/NormalModule/Domain/DomainClass.php
- tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleBench.php
- tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleConfig.php
- tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleDependencyProvider.php
- tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleFacade.php
- tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleFactory.php
We had phpbench tests for anonymous globals but not for a normal module before. So I added the same for a normal module structure.
> Add phpbench tests for a normal module

- src/Framework/AbstractConfig.php
- src/Framework/Config.php
- tests/Integration/Framework/UsingConfigWithDefaultValues/IntegrationTest.php
- tests/Integration/Framework/UsingConfigWithDefaultValues/LocalConfig/Config.php
- tests/Unit/Framework/ConfigTest.php
Currently, it's not possible to use `null` as default value for a non-defined config key.
- Allow `null` as default value as any other default value for config values.
> Allow null as default config value

- src/Framework/Config.php
- src/Framework/Config/ConfigInit.php
- tests/Integration/Framework/UsingConfigTypePhp/IntegrationTest.php
- tests/Integration/Framework/UsingConfigTypePhp/LocalConfig/Config.php
- tests/Integration/Framework/UsingConfigTypePhp/config/default.php
- tests/Integration/Framework/UsingConfigTypePhp/config/local.php
- tests/Integration/Framework/UsingConfigTypePhp/config/override.php
- Improve performance on Config->scanAllConfigFiles()
- Add an extra config file for `Integration/Framework/UsingConfigTypePhp` test
- This ensures/proof multi config file loading, overriding the previous one alphabetically
- The "local config file" will win the last override
> Minor clean up and test improvement

- src/Framework/ClassResolver/ClassResolverExceptionTrait.php
- src/Framework/Exception/Backtrace.php
- tests/Unit/Framework/Exception/BacktraceTest.php
The current Backtrace class is not testable, because it depends on the `\debug_backtrace()` native function.
- Move the `\debug_backtrace()` into a function, so it can be mocked and by doing so we can write tests for the `get()` behaviour.
If you use `createMock()` all methods are override in the mock, so if you want to mock only a certain function while keeping the real functionality from other methods, you have to use `createPartialMock`.
```php
$backtrace = $this->createPartialMock(Backtrace::class, ['getBacktraces']);
```
> Add unit tests for Backtrace

- CHANGELOG.md
- src/Framework/AbstractConfigGacela.php
- src/Framework/Config.php
- src/Framework/Config/ConfigLoader.php
- src/Framework/Config/GacelaConfigFileFactory.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- src/Framework/Gacela.php
- tests/Integration/Framework/UsingMultipleConfig/IntegrationTest.php
- tests/Unit/Framework/Config/ConfigInitTest.php
- tests/Unit/Framework/ConfigTest.php
We define custom configReaders as 3rd param in `Gacela::bootstrap()`. There are some disadvantages on this:
- More arguments for the `bootstrap()` increase the complexity of the main entry point of Gacela
- The configReaders are not possible to be defined in `gacela.php`
For these reasons, for example, I thought it will be better treating the `configReaders` the same as the existing `config` or `mappingInterfaces` concepts, which you are able to alter in your `gacela.php`, and also inside the `globalServices`.
- You can define in your `gacela.php` the `configReaders()` method
- You can define the `config-readers` as key in the `$globalServices`
- Change the bootstrap signature to this:
```php
final class Gacela
{
/**
* Define the entry point of Gacela.
*
* @param array<string,mixed> …
```
> Move config-readers as globalServices and gacela.php

- CHANGELOG.md
- src/Framework/Config.php
- src/Framework/Config/ConfigFactory.php
- src/Framework/Config/ConfigLoader.php
- src/Framework/Config/GacelaConfigFileFactory.php
- src/Framework/Config/PathNormalizer/AbsolutePathNormalizer.php
- src/Framework/Config/PathNormalizer/AbsolutePathStrategyInterface.php
- src/Framework/Config/PathNormalizer/NoEnvAbsolutePathStrategy.php
- src/Framework/Config/PathNormalizer/SuffixAbsolutePathStrategy.php
- src/Framework/Config/PathNormalizerInterface.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/IntegrationTest.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/LocalConfig/Config.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/LocalConfig/Facade.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/LocalConfig/Factory.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/config/default-dev.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/config/default-prod.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/config/default.php
- tests/Integration/Framework/UsingConfigFromCustomEnv/config/local.php
- tests/Unit/Framework/Config/ConfigInitTest.php
- tests/Unit/Framework/Config/PathNormalizer/NoEnvAbsolutePathStrategyTest.php
- tests/Unit/Framework/Config/PathNormalizer/SuffixAbsolutePathStrategyTest.php
Currently there is no possibility of defining some config for certain specific environment. So you end-up having the same config in all possible environments.
Added `APP_ENV` environment key, where you can define a value that you want, and that value will be added as suffix for your config file patterns.
When `APP_ENV=env` then this is order of reading the config files, so the latest overrides the previous key-values:
- default.php
- default-dev.php
- local.php (defined in the gacela.php under path_local key)
> Check the UsingConfigFromCustomEnv Integration tests.
Expose the possibility of creating custom `AbsolutePathStrategyInterface` via the globalInterfaces (when bootstrapping), and so, it would be interesting to be able to assign a particular path strategy to a concrete …
> Allow using config from custom env

- src/Framework/Config/ConfigGacelaMapper.php
- src/Framework/Config/ConfigLoader.php
- src/Framework/Config/GacelaConfigFileFactory.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php
- tests/Integration/Framework/Config/ConfigTest.php
- tests/Integration/Framework/UsingConfigTypePhp/gacela.php
- tests/Integration/Framework/UsingConfigWithBootstrapSetup/IntegrationTest.php
- tests/Integration/Framework/UsingMultipleConfig/IntegrationTest.php
The current `ConfigReaderInterface` has a method `canRead(): bool` which knows basically if they should read a file or not. There is no need to group them by file type.
- Remove unnecessary `type` key from the config
> Remove unnecesary type key from config

- composer.json
- composer.lock
Update dependencies & add `phpmetrics/phpmetrics`.
It's possible now run the command `composer metrics-report` in order to generate in `/data` folder a HTML folder with the project metrics.
> Add phpmetrics dependency

- CHANGELOG.md
- src/Framework/AbstractConfigGacela.php
- src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
- src/Framework/ClassResolver/ClassResolverFactory.php
- src/Framework/Config/GacelaConfigFileFactory.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- tests/Feature/Framework/CustomServices/FeatureTest.php
The custom services are relative to the module level using the namespace, not the paths. 
This is important because of the backslash that it's used such as:
- 'Infrastructure/Persistence' <- path
- 'Infrastructure\Persistence' <- namespace
- Renamed `custom-service-paths` to `custom-services-location` to make it clear that it's not linked to the path system.
- Set the day (today) for the new release version: 0.12.0 💡
> Rename custom-service-paths to custom-services-location

- CHANGELOG.md
- src/Framework/AbstractCustomService.php
- src/Framework/ClassResolver/CustomService/CustomServiceNotValidException.php
- src/Framework/ClassResolver/CustomService/CustomServiceResolver.php
- src/Framework/CustomServiceAwareTrait.php
- src/Framework/CustomServiceInterface.php
- tests/Feature/Framework/CustomServices/CustomModule/Application/InvalidGreeter.php
- tests/Feature/Framework/CustomServices/CustomModule/Application/ValidGreeter.php
- tests/Feature/Framework/CustomServices/CustomModule/Facade.php
- tests/Feature/Framework/CustomServices/FeatureTest.php
Currently the custom services must extend from AbstractCustomService, but it would be nice to don't force inheritance when it's not required. Although, with the AbstractCustomService you can use the getFactory() and getConfig() of the module, your custom services might don't need that, so the interface might be sufficient.
- Change from forcing extending `AbstractCustomService` to just implement `CustomServiceInterface`.
The advantage of using custom services is that they are accesible from gacela services AND they have an autoloader for their dependencies. The mapping-interfaces config is also available for the custom services too.
> 💡 Kudos to @JesusValera who gave me the idea.
> Custom services must implement CustomServiceInterface

- CHANGELOG.md
- composer.json
- src/Framework/AbstractConfigGacela.php
- src/Framework/Config/ConfigFactory.php
- src/Framework/Config/ConfigGacelaMapper.php
- src/Framework/Config/ConfigLoader.php
- src/Framework/Config/ConfigReader/PhpConfigReader.php
- src/Framework/Config/ConfigReaderInterface.php
- src/Framework/Config/GacelaConfigFileFactory.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php
- src/Framework/Config/PathNormalizer/AbsolutePathNormalizer.php
- src/Framework/Config/PathNormalizer/SuffixAbsolutePathStrategy.php
- src/Framework/Config/PathNormalizer/WithSuffixAbsolutePathStrategy.php
- src/Framework/Config/PathNormalizer/WithoutSuffixAbsolutePathStrategy.php
- src/Framework/Exception/Backtrace.php
- tests/Feature/Framework/UsingConfigFromCustomEnv/FeatureTest.php
- tests/Feature/Framework/UsingMultipleConfig/FeatureTest.php
- tests/Feature/Framework/UsingMultipleConfig/LocalConfig/Config.php
- tests/Feature/Framework/UsingMultipleConfig/LocalConfig/Domain/SimpleEnvConfigReader.php
- tests/Feature/Framework/UsingMultipleConfig/config/local.php
- tests/Integration/Framework/Config/ConfigTest.php
- tests/Unit/Framework/Config/ConfigInitTest.php
- tests/Unit/Framework/Config/PathNormalizer/SuffixAbsolutePathStrategyTest.php
- tests/Unit/Framework/Config/PathNormalizer/WithSuffixAbsolutePathStrategyTest.php
- tests/Unit/Framework/Config/PathNormalizer/WithoutSuffixAbsolutePathStrategyTest.php
Issue: https://github.com/gacela-project/gacela/issues/96
Currently, we have ConfigReaders as a separate key-value on gacela bootstrap level. This means that we iterate over all possible config paths across all existing ConfigReaders. This is not optimal for performance, because one ConfigReader wont be used for different file types.
```php
$globalServices = [
'config' => [
['path' => 'config/.env*'],
['path' => 'config/*.php'],
],
'config-readers' =>  [
new PhpConfigReader(),
new EnvConfigReader(),
],
];
```
```php
$globalServices = [
'config' => [
[
'reader' => new EnvConfigReader(),
'path' => 'config/.env*',
'path_local' => 'config/.env.local',
],
[
'reader' => new PhpConfigReader(),
'path' => 'config/*/*.php',
'path_local' => 'config/*/override.php',
],
],
];
```
Declare explicitly …
> Move ConfigReader next to the config path

- src/Framework/AbstractConfigGacela.php
- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/ClassResolver/ClassInfo.php
- src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
- src/Framework/ClassResolver/ClassNameFinder/ClassNameFinderInterface.php
- src/Framework/ClassResolver/ClassNameFinder/ClassValidator.php
- src/Framework/ClassResolver/ClassNameFinder/ClassValidatorInterface.php
- src/Framework/ClassResolver/ClassResolverExceptionTrait.php
- src/Framework/ClassResolver/ClassResolverFactory.php
- src/Framework/ClassResolver/ResolvableType.php
- src/Framework/Config/GacelaConfigFileFactory.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- src/Framework/Container/Exception/ContainerKeyNotFoundException.php
- tests/Feature/Framework/UsingCustomResolvableTypes/FeatureTest.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleA/ConfModuleA.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleA/DepProModuleA.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleA/FacadeModuleA.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleA/FactoryModuleA.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleB/ConfModuleB.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleB/DepProModuleB.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleB/FacadeModuleB.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleB/FactoryModuleB.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleC/Config.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleC/DependencyProvider.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleC/Facade.php
- tests/Feature/Framework/UsingCustomResolvableTypes/ModuleC/Factory.php
- tests/Feature/Framework/UsingCustomResolvableTypes/gacela.php
- tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Related to the issue: https://github.com/gacela-project/gacela/issues/105 although, it might not be exactly the "requested feature itself", I think this is an easier implementation that can help us get there if needed.
This allows you to define not just one replacement for the resolvable types keywords (Factory, Config, DependencyProvider) but now you can define multiple keywords for the same resolvable type.
You can have modules with different suffixes for Factories, Config, and DependencyProvider gacela classes, like:
```php
[
'Factory' => ['FactoryModuleA', 'FactoryModuleB', '...'],
'Config' => ['ConfModuleA', 'ConfModuleB'],
'DependencyProvider' => ['DepProModuleA', 'DepProModuleB'],
]
```
You could even define the default values in the begging and having as fallback other especial …
> Allow multiple overriding resolvable types

- src/Framework/Config/ConfigFactory.php
- src/Framework/Config/ConfigGacelaMapper.php
- src/Framework/Config/ConfigGacelaMapperInterface.php
- src/Framework/Config/FileIo.php
- src/Framework/Config/FileIoInterface.php
- src/Framework/Config/GacelaConfigFileFactory.php
- tests/Unit/Framework/Config/GacelaConfigFileFactoryTest.php
This is pointing to `feature/allow-multiple-resolvable-type-names` because otherwise we will face unnecessary conflicts (due to changes on the same files). **We can merge this PR (into master) once the other one gets merged first.**
- Create a `FileIoInterface` so we can create unit tests for `GacelaConfigFileFactory`.
> Make GacelaConfigFileFactory testable

- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/ClassResolver/ClassResolverExceptionTrait.php
- src/Framework/ClassResolver/GlobalInstance/AnonymousGlobal.php
- src/Framework/ClassResolver/ResolvableType.php
- src/Framework/Container/Locator.php
- tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php
- tests/Integration/Framework/GlobalServices/AnonymousClassesTest.php
- tests/Unit/Framework/ClassResolver/GlobalInstance/AnonymousGlobalTest.php
The class `AbstractClassResolver` has too many things inside. It clearly has one responsibility that can be extracted away: the responsibility of the anonymous globals.
-   Move to a separate class the "anonymous globals logic" from `AbstractClassResolver`.
> Separate the anonymous logic from the AbstractClassResolver

- src/Framework/Config/GacelaConfigBuilder/ConfigBuilder.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- tests/Feature/Framework/UsingConfigTypePhp/gacela.php
- tests/Feature/Framework/UsingConfigWithBootstrapSetup/FeatureTest.php
- tests/Feature/Framework/UsingMultipleConfig/FeatureTest.php
- tests/Fixtures/SimpleEnvConfigReader.php
- tests/Unit/Framework/Config/GacelaConfigBuilder/ConfigBuilderTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
The PhpConfigReader is the default config reader for gacela. I think it would be better to keep it as last optional argument when adding a new config reader.
Chnage the method signature for `ConfigBuilder->add()`:
```diff
-public function add(
-    $reader
-    string $path = GacelaConfigItem::DEFAULT_PATH,
-    string $pathLocal = GacelaConfigItem::DEFAULT_PATH_LOCAL,
-): self {
+public function add(
+    string $path,
+    string $pathLocal = '',
+    $reader = null
+): self {
```
> Move reader as last argument in ConfigBuilder->add() method

- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php
- src/Framework/ClassResolver/InstanceCreator/InstanceCreator.php
- src/Framework/Config/ConfigLoader.php
- src/Framework/Config/GacelaConfigFileFactoryInterface.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFileInterface.php
- tests/Fixtures/CustomClass.php
- tests/Fixtures/CustomClassWithDependencies.php
- tests/Fixtures/CustomInterface.php
- tests/Fixtures/StringValue.php
- tests/Integration/Framework/ClassResolver/InstanceCreator/InstanceCreatorTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
- tests/Unit/Framework/Fixtures/CustomClass.php
Separate the logic to create new instances from the `AbstractClassResolver` class.
No existing logic should be altered.
- Apply "extract class refactoring" in `AbstractClassResolver` to extract the `createInstance()` logic to its own class.
> Create a InstanceCreator class

- src/Framework/ClassResolver/ClassInfo.php
- tests/Benchmark/Framework/ClassResolver/ClassInfo/ClassInfoBench.php
- tests/Fixtures/ClassInfoTestingFacade.php
- tests/Unit/Framework/ClassResolver/ClassInfoTest.php
I was profiling Gacela (using [blackfire](https://blackfire.io/)) in order to find the slowest parts, and I found that `ClassInfo::fromObject()` is currently one of the most expensive places. So, I think adding a cache here make total sense.
- Added in memory cache to the result of `ClassInfo::fromObject()`, so it doesn't compute the same every time, instead it return the cached value (which is indeed a value object).
**LEFT**: Before (current master) -> `ClassInfo::fromObject()` is the first item (most expensive one).
**RIGHT**: After (current branch) -> `ClassInfo::fromObject()` is more efficient.
How did I performed this test? I created a test app with 16 modules (each of them with the basic Gacela files) and I load all of them a few hundreds of time. This is the code:
```php
<?php …
```
> Add cache to ClassInfo

- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- src/Framework/Gacela.php
- tests/Feature/Framework/BindingInterfacesWithInnerDependencies/FeatureTest.php
- tests/Feature/Framework/UsingConfigWithBootstrapSetup/FeatureTest.php
- tests/Feature/Framework/UsingMultipleConfig/FeatureTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
[Issue #124](https://github.com/gacela-project/gacela/issues/124)
From now on, instead of bootstrapping like this:
```php
Gacela::bootstrap($appRootDir, [
'global-services' => [],
'config' => function (ConfigBuilder $configBuilder): void {
// ...
},
'mapping-interfaces' => function (
MappingInterfacesBuilder $interfacesBuilder,
array $globalServices
): void {
// ...
},
'suffix-types' => function (SuffixTypesBuilder $suffixTypesBuilder): void {
// ...
},
]);
```
we can use constants in the `Gacela` class, like:
```php
Gacela::bootstrap($appRootDir, [
Gacela::GLOBAL_SERVICES => [],
Gacela::CONFIG => function (ConfigBuilder $configBuilder): void {
// ...
},
Gacela::MAPPING_INTERFACES => function (
MappingInterfacesBuilder $interfacesBuilder,
array $globalServices
): void {
// ...
}, …
```
> Create constants for Gacela::bootstrap() setup

- src/Framework/AbstractConfigGacela.php
- src/Framework/Config.php
- src/Framework/Config/ConfigFactory.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- src/Framework/Gacela.php
- src/Framework/Setup/AbstractSetupGacela.php
- src/Framework/Setup/SetupGacela.php
- src/Framework/Setup/SetupGacelaFactory.php
- src/Framework/Setup/SetupGacelaInterface.php
- tests/Feature/Framework/BindingInterfacesInGacelaConfigFile/gacela.php
- tests/Feature/Framework/BindingInterfacesWithInnerDependencies/gacela.php
- tests/Feature/Framework/UsingConfigTypePhp/gacela.php
- tests/Feature/Framework/UsingCustomSuffixTypes/gacela.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/FeatureTest.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/LocalConfig/Config.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/LocalConfig/Facade.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/LocalConfig/Factory.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/config/.env.omit
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/config/default.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/config/local.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/config/omit.yml
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/config/override.php
- tests/Feature/Framework/UsingDeprecatedAbstractConfigGacela/gacela.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
- tests/Unit/Framework/Setup/SetupGacelaFactoryTest.php
The current logic that it's used by `Gacela::bootstrap()` and `gacela.php` it's similar but different... The goal is to normalise these two places in order to facilitate its usage and experience.
- Deprecate `AbstractConfigGacela`, in favor of `SetupGacela`
```php
return static fn () => new class() extends AbstractConfigGacela {
public function config(ConfigBuilder $configBuilder): void
{
$configBuilder->add('config/*.php', 'config/local.php');
}
};
```
```php
return static fn () => (new SetupGacela())
->setConfig(
static function (ConfigBuilder $configBuilder): void {
$configBuilder->add('config/*.php', 'config/local.php');
}
);
```
> Create SetupGacela to replace AbstractConfigGacela

- tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php
Split the `AnonymousGlobalsBench` class, doing that, we should achieve a better score in Scrutinizer (currently this class' score is a **B**)
https://scrutinizer-ci.com/g/gacela-project/gacela/code-structure/master/operation/anonymous//tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php%244::setUp
> Split in methods the AnonymousGlobalsBench class

- CHANGELOG.md
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- src/Framework/Gacela.php
- src/Framework/Setup/AbstractSetupGacela.php
- src/Framework/Setup/SetupGacela.php
- src/Framework/Setup/SetupGacelaFactory.php
- src/Framework/Setup/SetupGacelaInterface.php
- tests/Feature/Framework/BindingInterfacesInGacelaConfigFile/gacela.php
- tests/Feature/Framework/BindingInterfacesWithInnerDependencies/FeatureTest.php
- tests/Feature/Framework/BindingInterfacesWithInnerDependencies/gacela.php
- tests/Integration/Framework/Config/ConfigFactory/ConfigFactoryTest.php
- tests/Integration/Framework/Config/ConfigFactory/WithGacelaFile/gacela.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
[Issue link](https://github.com/gacela-project/gacela/issues/131)
The origin of the `globalService` concept started as a "bag" where we define all `Gacela` framework configuration, over the time, we move this configuration/setup to specific callables, but the name was still there and losing meaning.
At this point, the `globalService` key in the setup was only for link external services from the exterior to the Gacela framework, in this scenario, the idea of `externalService` makes much more sense.
- Rename the `globalService` method/properties to `externalService`
- Deprecate the original `globalService` method from the setup
> Rename the concept of GlobalServices to ExternalServices

- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/ClassResolver/ClassInfo.php
- src/Framework/ClassResolver/ClassResolverExceptionTrait.php
- src/Framework/ClassResolver/Config/ConfigNotFoundException.php
- src/Framework/ClassResolver/Config/ConfigResolver.php
- src/Framework/ClassResolver/DependencyProvider/DependencyProviderNotFoundException.php
- src/Framework/ClassResolver/DependencyProvider/DependencyProviderResolver.php
- src/Framework/ClassResolver/Facade/FacadeNotFoundException.php
- src/Framework/ClassResolver/Facade/FacadeResolver.php
- src/Framework/ClassResolver/Factory/FactoryNotFoundException.php
- src/Framework/ClassResolver/Factory/FactoryResolver.php
- src/Framework/Container/Exception/ContainerKeyNotFoundException.php
- src/Framework/FacadeResolverAwareTrait.php
- tests/Benchmark/Framework/ClassResolver/ClassInfo/ClassInfoBench.php
- tests/Feature/Framework/FacadeAware/FeatureTest.php
- tests/Feature/Framework/FacadeAware/Module/Command/TestHiCommand.php
- tests/Feature/Framework/FacadeAware/Module/Facade.php
- tests/Feature/Framework/FacadeAware/Module/UserInput/Command/TestHiCommand.php
- tests/Feature/Framework/FacadeAware/config/default.php
- tests/Unit/Framework/ClassResolver/ClassInfoTest.php
Issue: https://github.com/gacela-project/gacela/issues/136
In the context of a module, allow the auto-wiring of the `Facade` of the module on a specific/custom folder.
Consider the following example. Given these two classes:
```php
App\MyModule\MyModuleFacade;
App\MyModule\Command\HelloCommand;
```
The class `HelloCommand` should have access to the `MyModuleFacade` using `getFacade()`.
Until now, we construct these classes in the Factory, where we inject the Facade on it, but this is a bit odd. And it doesn't feel right. The reason is that the Command belongs to the infrastructure layer, therefore I should be able to talk to the Facade directly using Gacela's auto-wiring.
Allow accessing the `Facade` of the module from a subfolder of 1 level.
- Prepare failing test related to FacadeAware …
> Make the Facade accesible from module-internal subfolders

- .gitignore
- composer.json
- composer.lock
- phpmetrics-config.json
- Execute only on `src` (not on `tests` dir!)
- Now we can see two new sections in the menu: "Unit testing" and "Git"
- Added a new composer script command that trigger all test suites and generates a fresh report inside the ignored `data` dir (you just need to open `data/metrics-report/index.html` in your local browser)
An overview of the menu.
> Improve phpmetrics usage

- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
Related issue: #101 
This PR allows returning a `SetupGacela` instance instead of a callable directly from the `gacela.php` file.
> Allow to return an instance of SetupGacela on gacela.php

- CHANGELOG.md
- src/Framework/Config/GacelaConfigBuilder/SuffixTypesBuilder.php
- src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
- tests/Feature/Framework/UsingCustomSuffixTypes/FeatureTest.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleA/CommandModuleA.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleA/FactModuleA.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleA/FaçModuleA.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleB/CommandModuleB.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleB/ConfigModuleB.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleB/DependencyProviderModuleB.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleB/FactoryModuleB.php
- tests/Feature/Framework/UsingCustomSuffixTypes/ModuleC/CommandModuleC.php
- tests/Feature/Framework/UsingCustomSuffixTypes/gacela.php
- tests/Integration/Framework/Config/ConfigFactory/ConfigFactoryTest.php
- tests/Integration/Framework/Config/ConfigFactory/WithGacelaFile/gacela.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/GacelaConfigFileTest.php
:octocat: Github Issue: https://github.com/gacela-project/gacela/issues/138
This PR enables to define the `addFacade()` method to the `SuffixTypesBuilder` as follows:
```php
->setSuffixTypes(static function (SuffixTypesBuilder $suffixTypesBuilder): void {
$suffixTypesBuilder
->addFacade('FacadeFileName')
->addFactory('...')
->addConfig('...')
->addDependencyProvider('...');
});
```
By doing this, the user is able to decouple from the `Gacela` predetermined naming convention, and with annotations, execute from any entry point (command, controller...) the logic from his domain through the facade 🎉
> Add addFacade to SuffixTypesBuilder class

- CHANGELOG.md
- src/Framework/Bootstrap/AbstractSetupGacela.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
The `globalServices` method was renamed to `externalServices` two versions ago, we decided to change the name but keep the original method for backward compatibility.
I think we gave enough time to this method, we can drop it in this PR.
As the PhpDoc mentioned, if you were using the `globalServices`, you only have to switch to the new `externalServicies`, everything should work as it was.
> Remove deprecated globalServices() from Setup

- src/Framework/Bootstrap/AbstractSetupGacela.php
- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- tests/Feature/Framework/BindingInterfacesWithInnerDependencies/FeatureTest.php
- tests/Feature/Framework/BindingInterfacesWithInnerDependencies/gacela.php
In this PR, the PhpDoc from `externalServices` method was changed
- from `/** @var array<string,mixed> */`
- to `/** @var array<string,class-string|object|callable> */`
I think it doesn't make sense to add to `externalServices` any other kind rather than a callable, object or class-string, as the final purpose of this method is to pass external services (e.g: framework services) rather than booleans or any other type.
> I marked the PR as `under discussion` because we need to think a bit longer about this change, but I don't see any other scenario where a string or bool as an external service could have sense.
> Change PhpDoc from $externalServices

- src/Framework/Bootstrap/GacelaConfig.php
- tests/Feature/Framework/UsingConfigFromCustomEnv/FeatureTest.php
- tests/Feature/Framework/UsingConfigWithBootstrapSetup/FeatureTest.php
- tests/Feature/Framework/UsingCustomSuffixTypes/FeatureTest.php
- Define `config/local.php` in `GacelaConfig::withPhpConfigDefault()`
- Use `GacelaConfig::withPhpConfigDefault()` in tests
> Define local pattern php config default 

- CHANGELOG.md
- src/Framework/ClassResolver/AbstractClassResolver.php
Create `AbstractClassResolver::resetCache()` method in order to remove the cache, this function is focus for tests when using `@dataproviders` for example.
> Add AbstractClassResolver::resetCache()

- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/Gacela.php
Allow disabling the cache for gacela resolved classes (facade, factory, config, dependency-provider). 
It's enable by default (keeping the backward compatibility), but you can disable from the config like:
```php
public function setUp(): void
{
$configFn = static function (GacelaConfig $config): void {
$config->addAppConfig('config/*.php', 'config/local.php');
$config->setClassResolverCached(false); # <---- THIS IS THE NEW THING :)
};
Gacela::bootstrap(__DIR__, $configFn);
}
```
- Add `AbstractClassResolver::resetCache()` inside `Gacela::bootstrap()` when the cache is disabled for class resolver.
> Reset cache from class resolver when bootstrapping

- src/Framework/DocBlockResolverAwareTrait.php
It was not possible to use the trait `DocBlockResolverAwareTrait` on Laravel's Controller, because the signature from `__call()` was different to the signature we had, so, we implement the signature from there to make it work 😄
> Solve FatalError incompatible declaration in Laravel

- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- tests/Feature/Framework/UsingCustomSuffixTypes/FeatureTest.php
- tests/Integration/Framework/Config/ConfigTest.php
- tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
- tests/Unit/Framework/ClassResolver/DocBlockService/DocBlockParserTest.php
- tests/Unit/Framework/ClassResolver/DocBlockService/UseBlockParserTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
- Change `callable` to `Closure` in PhpDoc for `GacelaConfig::withPhpConfigDefault()`
- Mark some classes as `final`
- Define `setUp()` from tests as `public`
- Check the `$config->addExternalService()`, the 2nd parameter is a closure
> Small code improvements

- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
- src/Framework/Config/Config.php
- src/Framework/Gacela.php
- tests/Integration/Framework/Config/ConfigTest.php
- tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Rename flag `classResolverCached` to `resetCache` (the default value now is `false`).
Also, when you select you really want to reset the Gacela cache, you will reset all caches, including:
- ClassNameFinder::resetCachedClassNames()
- AbstractClassResolver::resetCache()
- Config::resetInstance()
So, we don't need to use the `@internal`s method anymore for an specific test, with the `$config->setResetCache(true)` is enough. 
I was thinking and I have some alternatives to `resetCache`, e.g:
- resetCacheOnBootstrap
- resetGacelaCache
- classResolverCached (the old one, I think it's outdated...)
- you say! ...
> Rename config key from setClassResolverCached() to setResetCache()

- src/Framework/DocBlockResolverAwareTrait.php
- tests/Integration/Framework/DocBlockResolverAware/BadDummyDocBlockResolverAware.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverAwareTest.php
When `DocBlockResolverAwareTrait` uses `parent::class` without checking if there is or not a parent class then you might face this  ```Error: Cannot use "parent" when current class scope has no parent```.
- Check if the current class has a parent before accessing the `parent::class` .
> Doc block resolver aware with no parent

- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Gacela.php
- tests/Benchmark/Framework/ClassResolver/ClassNameCache/ClassNameCacheBench.php
- tests/Integration/Framework/Config/ConfigTest.php
- tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Rename the GacelaConfig method from `$config->resetCache(bool)` to `$config->setCacheEnabled(bool)`.
The default value is now `true`.
> Rename $config->resetCache() to $config->setCacheEnabled()

- src/Framework/ClassResolver/AbstractFileCache.php
- src/Framework/ClassResolver/Cache/GacelaCache.php
- src/Framework/ClassResolver/ClassResolverFactory.php
- src/Framework/ClassResolver/InMemoryCache.php
- src/Framework/ClassResolver/InMemoryFileCache.php
- src/Framework/Config/Config.php
- src/Framework/DocBlockResolverAwareTrait.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverInMemoryAwareTest.php
- tests/Integration/Framework/DocBlockResolverAware/config/custom-services/default.php
- tests/Integration/Framework/DocBlockResolverAware/config/in-memory/default.php
- tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Currently the gacela cache files are created under the root project dir.
- Create a directory "cache" on the fly in case it does not exists.
- Store inside the "cache" directory the cache files.
- Allow enable/disable the cache from the config files directly.
> Group gacela cache files inside a cache directory

- CHANGELOG.md
- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Config/Config.php
- tests/Feature/CodeGenerator/MakeFileCommandTest.php
- tests/Feature/CodeGenerator/MakeModuleCommandTest.php
- tests/Feature/Framework/CustomCacheDirectory/FeatureTest.php
- tests/Feature/Framework/CustomCacheDirectory/Module/Facade.php
- tests/Feature/Framework/CustomCacheDirectory/Module/Persistence/FakeRepository.php
- tests/Feature/Util/DirectoryUtil.php
Right now the cache directory name is fixed as `cache`.
- Added `setCacheDirectory()` to `GacelaConfig`
> Allow defining custom cache directory name

- CHANGELOG.md
- src/Framework/ClassResolver/AbstractFileCache.php
- tests/Feature/Framework/CustomCacheDirectory/FeatureTest.php
Currently, `$config->setCacheDirectory('custom-caching-dir');` doesn't work if you points to a non existing directory with multiple nested level; for example `'custom/caching-dir'`.
- Fix nested directly levels for the cache directory.
> Fix setCacheDirectory() with nested dir levels

- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/ClassResolver/Cache/GacelaCache.php
- src/Framework/ClassResolver/ClassResolverFactory.php
- src/Framework/DocBlockResolverAwareTrait.php
- tests/Integration/Framework/DocBlockResolverAware/config/custom-services/default.php
- tests/Integration/Framework/DocBlockResolverAware/config/in-memory/default.php
- Refactor the `GacelaCache` constant names
- Change the default cache-dir name from `cache` to `data/cache`
> Refactor gacela cache default values

- src/Framework/ClassResolver/Cache/GacelaCache.php
The gacela cache directly name is still customisable when bootstrapping gacela. But, by default, I think it's better to group the generated files under a directory named `.gacela/`.
- Change `DEFAULT_DIRECTORY_VALUE` to `.gacela/cache`
> Change cache default directory to .gacela/cache

- src/Framework/Config/ConfigFactory.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/FeatureTest.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Config.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/default.php
Having a `gacela.php` and a `gacela-prod.php` file.
If we define the `APP_ENV` as `dev`
1. `gacela.php` should be loaded
When we define the `APP_ENV` as `prod`
1. `gacela.php` should be loaded
2. `gacela-prod.php` should be loaded right after (overriding the keys if repeated)
> Load both gacela.php and gacela-xxx.php files

- CHANGELOG.md
- src/Framework/Config/ConfigFactory.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/FeatureTest.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Config.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Facade.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/LocalConfig/Factory.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/default.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/dev.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/config/prod.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/gacela-dev.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/gacela-prod.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/gacela.php
Issue: #95
Load a custom `gacela-*.php` file depending on the `APP_ENV` environment variable.
Currently, we have something similar for application config key-values, for example: 
- `config/file.php` # putenv('APP_ENV'); // empty
- `config/file-test.php` # putenv('APP_ENV=test');
- `config/file-prod.php` # putenv('APP_ENV=prod');
The idea is to have something like this:
- `gacela.php` # putenv('APP_ENV'); // empty
- `gacela-test.php` # putenv('APP_ENV=test');
- `gacela-prod.php` # putenv('APP_ENV=prod');
> **Note**: Depending on the `APP_ENV` it will load a different file.
- Check the `APP_ENV` in the `ConfigFactory` when reading the gacela file
> Gacela configuration for different environments 

- phpunit.xml
Increase Code Coverage from 87% to 94% excluding some files from `src/CodeCoverage` module.
We already have [excellent `feature` tests for the module](https://github.com/gacela-project/gacela/tree/master/tests/Feature/CodeGenerator), so, those classes are being "tested" indirectly through PHP `exec()` command. Still, unfortunately, they are not included in the PHPUnit coverage, and because of that, the code coverage drops 7 points.
I think the best alternative is just ignore them 😄
> Increase Code Coverage excluding some files

- CHANGELOG.md
- composer.json
- src/Framework/Bootstrap/GacelaConfig.php
- tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/FeatureTest.php
- tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/Module/Config.php
- tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/Module/Facade.php
- tests/Feature/Framework/AddAppConfigKeyValuesInGacelaBootstrap/Module/Factory.php
📚 Description
Issue: https://github.com/gacela-project/gacela/issues/178 - _part 2_
Continuation of https://github.com/gacela-project/gacela/pull/183#discussion_r921013044 🤠 
🔖 Changes
Add method: `GacelaConfig->addAppConfigKeyValues( array<string, mixed> )`
> Create addAppConfigKeyValues() from GacelaConfig

- CHANGELOG.md
- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/ClassResolver/Cache/GacelaCache.php
- src/Framework/ClassResolver/ClassResolverFactory.php
- src/Framework/Config/Config.php
- src/Framework/Config/ConfigInterface.php
- src/Framework/DocBlockResolverAwareTrait.php
- tests/Feature/Framework/CustomCacheDirectory/FileCacheFeatureTest.php
- tests/Feature/Framework/CustomCacheDirectory/NoFileCacheFeatureTest.php
- tests/Feature/Framework/CustomNoCacheDirectory/Module/Facade.php
- tests/Feature/Framework/CustomNoCacheDirectory/Module/Persistence/FakeRepository.php
- tests/Feature/Framework/CustomNoCacheDirectory/NoFileCacheFeatureTest.php
- tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/FeatureTest.php
- tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/Module/Config.php
- tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/Module/Facade.php
- tests/Feature/Framework/GacelaConfigAddAppConfigKeyValues/Module/Factory.php
- tests/Unit/Framework/ClassResolver/Cache/GacelaCacheTest.php
Issue https://github.com/gacela-project/gacela/issues/185
When the cache is disabled (from the application configs or the bootstrap), any `*.cache` file will be generated.
- Extends `GacelaCache` file
- Introduce `ConfigInterface`
> Fixing setCacheEnable behaviour

- src/Framework/DocBlockResolver/DocBlockResolvable.php
- src/Framework/DocBlockResolver/DocBlockResolver.php
- src/Framework/DocBlockResolverAwareTrait.php
The current `DocBlockResolverAwareTrait` has too much logic, and it's really hard to follow what's going on. Especially, considering that this trait is something that the user will use on their end.
- Apply "extract class refactoring" on `DocBlockResolverAwareTrait` to improve the readability of the trait logic itself.
> **Note**: We have a full test coverage on this area under `GacelaTest\Integration\Framework\DocBlockResolverAware`.
> Extract class refactoring in DocBlockResolverAwareTrait

- src/Framework/DocBlockResolverAwareTrait.php
I remember we faced some errors when in Laravel a `Controller` class, a userland use the `DocBlockResolverAwareTrait`.
This error was happening because both (the trait and the controller) implemented the magic `__call()` method. In some scenarios, when the trait was implemented, it was overriding the `__call()` from the controller facing some undesirable effects.
It seems that this error is not happening anymore in Laravel (I could not reproduce this scenario), so, I decided to remove this _dead_ code from now.
> Remove dead code from DocBlockResolverAwareTrait

- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- tests/Feature/Framework/UsingCustomSuffixTypes/gacela.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
- Remove the deprecated possibility of returning a `SetupGacelaInterface` from `gacdela.php`
- Use `callable(GacelaConfig)` instead.
> Remove deprecated SetupGacelaInterface from gacela.php

- CHANGELOG.md
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Gacela.php
Currently, `Gacela::bootstrap()` load only the configFn that it's passed as 2nd arg or uses default values. There is no way to let Gacela know to use your custom gacela.php file to take the configFn setup from there.
Added a new condition on `Gacela::bootstrap()` in order to fetch the `configFn` that will initialize the "SetupGacela" values.
> Process configFn from appRootDir if exists, and it wasn't defined on bootstrap

- src/Console/ConsoleConfig.php
- tests/Feature/CodeGenerator/MakeFileCommandTest.php
- tests/Feature/CodeGenerator/MakeModuleCommandTest.php
- tests/Feature/CodeGenerator/composer.json
There is no behaviour/logic change in this PR, just refactoring the existing tests for the CodeGenerator feature in order to count the code coverage for this feature as well.
Instead of using the `exec(...)` use the actual Command `new MakeFileCommand(...)` and run it in the test.
> Scrunitizer build: https://scrutinizer-ci.com/g/gacela-project/gacela/inspections/097747bd-d19e-4dba-8640-00fd22613b2a
> Refactor CodeGenerator tests to include them in the code coverage

- phpstan.neon
- src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
Add to `phpstan.neon` the rule to ignore when a `class-string` should be returned but returns a `string` and clean a little the code 😄
> Fix PHPStan error should return class-string but returns string

- src/Console/ConsoleConfig.php
- src/Console/Domain/ConsoleException.php
- src/Framework/Config/Config.php
- tests/Feature/CodeGenerator/MakeExceptionCommandTest.php
- tests/Feature/CodeGenerator/MakeFileCommandTest.php
- tests/Feature/CodeGenerator/MakeModuleCommandTest.php
- tests/Integration/Framework/Config/ConfigTest.php
There were still some areas without code coverage.
- Normalize the `appRootDir`
- Introduce custom `ConsoleException::composerJsonNotFound()` instead of a generic `LogicException` when the composer.json file is not found (when using the gacela make commands)
- Improve the code coverage over the Gacela/Console module
---
You can verify the code coverage running this in your local:
```bash
composer test-coverage
```
> Full code coverage on Gacela/Console module

- src/Framework/ClassResolver/AbstractClassResolver.php
We are not currently caching (in memory) the default gacela class after been resolved.
- Update `doResolve()` to cache the "defaultGacelaClass" after been resolved as any other resolved class
> Cache default resolved gacela class

- .gitignore
- CHANGELOG.md
- composer.json
- src/Console/Domain/CommandArguments/CommandArgumentsParser.php
- tests/Feature/CodeGenerator/MakeModuleCommandTest.php
- tests/Feature/CodeGenerator/composer.json
Right now the gacela make commands works only for the psr-4 provided in the autoload, not autoload-dev.
- Read autoload and autoload-dev from composer.json to fetch the possible psr-4 values.
> Read autoload dev when parsing composer

- CHANGELOG.md
- src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefix.php
- src/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefix.php
- tests/Unit/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefixTest.php
- tests/Unit/Framework/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefixTest.php
Currently, it's not possible to have a simple project with only 1 level in the namespace.
- Allow optional project namespace on class name finder rules.
> Allow optional project namespace on class name finder rules

- src/Framework/ClassResolver/DocBlockService/UseBlockParser.php
- src/Framework/DocBlockResolver/DocBlockResolver.php
- tests/Unit/Framework/ClassResolver/DocBlockService/UseBlockParserTest.php
The value of the profiler/cache files resulting from the `UseBlockParser` is missing the left `\` char in the files `gacela-custom-services.json`. We currently have for the `gacela-class-names.json` file, so we want to keep that left char in both files.
> Normalize UseBlockParser

- src/Framework/Config/PathFinder.php
The `glob()` signature is actually:
```php
function glob(string $pattern, int $flags = 0): array|false {}
```
Which means that it returns an `array` or `false`. Therefore, we can use the [Elvis operator](https://en.wikipedia.org/wiki/Elvis_operator) here to simplify the code.
- Simplify the `PathFinder::matchingPattern()` using the [Elvis operator](https://en.wikipedia.org/wiki/Elvis_operator).
> Refactoring PathFinder::matchingPattern()

- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/EventListener/EventDispatcher.php
- tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php
- tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php
- tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverSpecificListenerTest.php
- tests/Feature/Framework/ListeningEvents/ConfigReader/GacelaConfigReaderListenerTest.php
We added the possibility to register a listener to a particular event https://github.com/gacela-project/gacela/pull/215 
It would be useful to be able to register a listener to all posible events.
- Added `registerGenericListener()` to be able to register a generic listener for all events.
```php
GacelaConfig::registerGenericListener(callable $listener): void
```
```php
$renderEvent = static function (GacelaEventInterface $event): void {
echo sprintf("%s - %s\n", \get_class($event), $event->toString());
};
Gacela::bootstrap(__DIR__, static function (GacelaConfig $config) use ($renderEvent): void {
// All of these individual specific listeners
$config->registerSpecificListener(ResolvedClassCachedEvent::class, $renderEvent);
$config->registerSpecificListener(ResolvedClassCreatedEvent::class, …
```
> Add GacelaConfig::registerGenericListener()

- src/Framework/AbstractConfig.php
- src/Framework/Config/Config.php
- src/Framework/Gacela.php
- tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php
Simplify the Config initialisation by forcing passing the `GacelaSetup` while constructing the `Config` singleton. 
Before, `getInstance()` was creating a new instance in case there was none. Now, the creation of the `Config` singleton happens only with `Config::createWithSetup($setup)` not on `getInstance()` anymore.
> Add Config::createWithSetup()

- src/Console/Domain/FilenameSanitizer/FilenameSanitizer.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/FakeEvent.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php
With this you will be able to override the gacela listeners from a project that uses a library on top of gacela. 
> For example: `phel-snake` --(which uses)-> `phel-lang` --(which uses)-> `gacela`
Currently from `phel-snake` you are not able to alter any `gacela` configuration. You can play only with the configuration that `phel-lang` exposes to you. Which make sense "by default", but there are certain things that would be good to be able to expose to any level from gacela point of view; eg **registering listeners** for `gacela events`.
- Allow registering listeners using `gacela.php` configuration file from a project which uses gacela as vendor of a vendor.
> Add overrideEventDispatcher() to SetupGacela

- src/Framework/ClassResolver/AbstractClassResolver.php
- tests/Feature/Framework/ResolveDifferentProjectNamespaces/FeatureTest.php
- tests/Feature/Framework/UsingCustomSuffixTypes/FeatureTest.php
Before we were creating a new instance of `ClassNameFinder` for each resolvable, which doesn't make much sense. Instead, we can keep it static, so this is a share object between all "Class Resolvers" which will improve the performance.
- Make static the ClassNameFinder from AbstractClassResolver
Let's consider I introduce a listener inside the `phel-snake` project to see which events are triggered: 
```php
return static function (GacelaConfig $config): void {
$config->registerGenericListener(static function (GacelaEventInterface $event): void {
echo $event->toString() . PHP_EOL;
});
};
```
Notice there are a lot of `InMemoryCacheCreatedEvent`:
There is just one `InMemoryCacheCreatedEvent`:
> Make static the ClassNameFinder

- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- tests/Unit/Framework/Bootstrap/SetupGacelaTest.php
This PR is a follow up PR of https://github.com/gacela-project/gacela/pull/222 Currently there is no possibility of overriding or combine different `SetupGacela` objects. Just overriding the `eventDispatcher`.
- Rename `overrideEventDispatcher()` to `combine()`
- Instead of creating a new `eventDispatcher`, create a new `ConfigurableEventDispatcher` if there was none before
- combine ExternalServices
- combine ProjectNamespaces
- combine ConfigKeyValues
- combine EventDispatcher
- override ResetInMemoryCache
- override FileCacheSettings
> Combine and override different SetupGacela objects

- src/Framework/ClassResolver/AbstractClassResolver.php
- src/Framework/ClassResolver/Cache/AbstractPhpFileCache.php
- src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
- src/Framework/ClassResolver/ClassResolverCache.php
- src/Framework/ClassResolver/ClassResolverFactory.php
- src/Framework/Config/ConfigReader/PhpConfigReader.php
- src/Framework/DocBlockResolver/DocBlockResolver.php
- src/Framework/DocBlockResolver/DocBlockResolverCache.php
- src/Framework/Event/ClassResolver/Cache/ClassNameCacheCachedEvent.php
- src/Framework/Event/ClassResolver/Cache/ClassNameInMemoryCacheCreatedEvent.php
- src/Framework/Event/ClassResolver/Cache/CustomServicesCacheCachedEvent.php
- src/Framework/Event/ClassResolver/Cache/CustomServicesInMemoryCacheCreatedEvent.php
- src/Framework/Event/ClassResolver/Cache/CustomServicesPhpCacheCreatedEvent.php
- src/Framework/Event/Dispatcher/EventDispatchingCapabilities.php
- src/Framework/Gacela.php
- tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverInMemoryAwareTest.php
I discover a clear issue with the current implantation for the `PhpFileCache`, because this one was actually slower than the `InMemoryCache`. After some investigation I found that the object holding the `PhpFileCache` was actually being created every time instead of keeping itself cached. I found this thanks to the internal event system we introduced last week.
- Add more internal events for the `ClassResolver\Cache` scope
- Fix the `PhpFileCache` holding a unique cache across the project, which boost the performance by almost 50%
And comparing master with this branch:
> **Note**: The performance boost is crazy good ⚡ Thanks @dantleech for PHPBench!
> Fix PhpFileCache

- src/Framework/DocBlockResolver/DocBlockResolvable.php
- src/Framework/DocBlockResolver/DocBlockResolver.php
- tests/Integration/Framework/DocBlockResolver/DocBlockResolverTest.php
- tests/Integration/Framework/DocBlockResolver/Module/FakeCommand.php
- tests/Integration/Framework/DocBlockResolver/Module/FakeConfig.php
- tests/Integration/Framework/DocBlockResolver/Module/FakeFacade.php
- tests/Integration/Framework/DocBlockResolver/Module/FakeFactory.php
- tests/Integration/Framework/DocBlockResolver/Module/FakeRandomService.php
Right now, when using the `DocBlockResolverAwareTrait` we are saving the full class name as resolvableType, which is not "totally optimal" for the internal gacela class names such as Facade, Factory and Config. Those are saved internally without the module prefix, especially when using the file cache system. 
- Avoid using the module prefix as `resolvableType` when using `DocBlockResolverAwareTrait`
> Optimize DocBlockResolver resolvableType

- src/Framework/DocBlockResolverAwareTrait.php
Fixing DocBlockResolverAwareTrait cache.
> Fixing DocBlockResolverAwareTrait cache

- src/Framework/ClassResolver/AbstractClassResolver.php
The `AbstractClassResolver->doResolve()` method is exposed as `public`, but it should be `protected` instead.
> Change to protected AbstractClassResolver->doResolve()

- src/Framework/Container/Exception/ContainerException.php
Remove the useless `ContainerException::notFound()` method.
> Remove useless ContainerException::notFound()

- src/Framework/Container/Container.php
- src/Framework/Container/Exception/ContainerException.php
- tests/Unit/Framework/Container/ContainerTest.php
Issue: https://github.com/gacela-project/gacela/issues/233
- Freeze a "used `Container` service" (using `get()`) to avoid altering it after its first usage.
> Frozen used Container services

- CHANGELOG.md
- src/Framework/Container/Container.php
- src/Framework/Container/Exception/ContainerException.php
- tests/Unit/Framework/Container/ContainerTest.php
Currently, the `DependenyProvider` can define only services that will be resolved on the `Factory`. There is no way to define a service that won't be resolved for any reason.
This PR is about allowing the creation of a service(callable) that won't be resolved when it's been used.
- A protected service wont be resolved when it's used
- A protected service cannot be extended
> Add Container::protect()

- CHANGELOG.md
- src/Framework/Container/Container.php
- tests/Unit/Framework/Container/ContainerTest.php
Currently it's possible to extend a service only when using a callable or an object, but not a raw array.
- Allow extending array services. Similar behaviour as we currently do when extending objects
> Allow extending raw arrays as services

- tests/Feature/Framework/FileCache/FileCacheFeatureTest.php
Sometimes there "gacela cache files" are not deleted (even after running all tests), because the feature test which enable them contains was trigger the latest, and then it remains that state for some tests that are running afterwards:
- Ensure that we disable the "gacela file cache" on the `tearDownAfterClass()`
> Disable file cache after running feature tests

- CHANGELOG.md
- src/Framework/Container/Locator.php
- tests/Unit/Framework/Container/LocatorTest.php
Similar to the [comment](https://github.com/gacela-project/gacela/pull/203#pullrequestreview-1129816016) I wrote at [Allow using Interface suffix for DocBlockResolver](https://github.com/gacela-project/gacela/pull/203).
We should not depend on the class name to resolve a class from its interface.
This PR aims to remove the logic from the locator that adds some magic to the code and makes it less explicit.
> Locator should not resolve interfaces magically

- src/Framework/Container/Container.php
- src/Framework/Container/ContainerInterface.php
- src/Framework/Container/Exception/ContainerException.php
- tests/Unit/Framework/Container/ContainerTest.php
- `Container::factory()` and `Container::protect()` expects a `Closure`
> Normalize ContainerInterface

- .github/workflows/ci.yml
- CHANGELOG.md
- composer.json
As 7.4 is [not supported anymore](https://www.php.net/supported-versions.php), I would encourage everyone to upgrade to at least 8.0 (or higher), in order to avoid accumulating more tech debt as time passes by...
- Drop support for PHP 7.4
This unlock the project to use the [new features that comes with PHP 8.0 ](https://www.php.net/releases/8.0/en.php).
> Drop support for PHP 7.4

- src/Framework/ClassResolver/ClassInfo.php
- src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php
- src/Framework/ClassResolver/ClassResolverCache.php
- src/Framework/Event/ClassResolver/AbstractGacelaClassResolverEvent.php
- src/Framework/Event/ClassResolver/Cache/ClassNameCacheCachedEvent.php
- src/Framework/Event/ClassResolver/Cache/ClassNameInMemoryCacheCreatedEvent.php
- src/Framework/Event/ClassResolver/Cache/ClassNamePhpCacheCreatedEvent.php
- src/Framework/Event/ClassResolver/Cache/CustomServicesCacheCachedEvent.php
- src/Framework/Event/ClassResolver/Cache/CustomServicesInMemoryCacheCreatedEvent.php
- src/Framework/Event/ClassResolver/Cache/CustomServicesPhpCacheCreatedEvent.php
- src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameCachedFoundEvent.php
- src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameInvalidCandidateFoundEvent.php
- src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameNotFoundEvent.php
- src/Framework/Event/ClassResolver/ClassNameFinder/ClassNameValidCandidateFoundEvent.php
- src/Framework/Event/ConfigReader/ReadPhpConfigEvent.php
- src/Framework/Event/Dispatcher/ConfigurableEventDispatcher.php
Currently the Events `toString()` return the event class name plus some additional data, but there is no standard.
I want to standardise with something like `EventName {property1:"value1", property2:"value2"}`
- Normalize toString() from all internal events
> Normalize toString() from all internal events

- src/Framework/Config/ConfigFactory.php
- src/Framework/Gacela.php
- tests/Feature/Framework/AnonymousGlobalExtendsExistingClass/FeatureTest.php
- tests/Feature/Framework/BindingInterfacesInGacelaConfigFile/FeatureTest.php
- tests/Feature/Framework/BindingInterfacesWithInnerDependencies/FeatureTest.php
- tests/Feature/Framework/UsingConfigFromCustomEnv/FeatureTest.php
- tests/Feature/Framework/UsingConfigTypePhp/FeatureTest.php
- tests/Feature/Framework/UsingConfigWithBootstrapSetup/FeatureTest.php
- tests/Feature/Framework/UsingGacelaFileFromCustomEnv/FeatureTest.php
- tests/Feature/Framework/UsingMultipleConfig/FeatureTest.php
- tests/Integration/Framework/Config/ConfigFactory/ConfigFactoryTest.php
I found a bug when registering specific listeners [with `PhelConfig::registerSpecificListener()`] that when creating the GacelaFileConfig object [`createGacelaFileConfig()`] when defined in `$gacelaPhpDefaultPath` (aka at the root of a project which uses Gacela in vendor), then it was calling twice the `createGacelaFileConfig()` which is mutating the `bootstrapSetup` combining it with the `$projectSetupGacela`. This ended up into a duplication of "specific listeners".
The solution is rather simple, just keep a singleton copy of the `GacelaFileConfig` in memory, because once it's generated it wont change it during the execution of the program.
- Add `GacelaFileConfig` as a memory cache to `ConfigFactory`
> Add cache GacelaFileConfig to ConfigFactory

- composer.json
This tool allow us to run composer scripts in parallel. 
> **Note**: More about it here: https://veewee.github.io/blog/run-composer-tasks-in-parallel/
- Install --dev `veewee/composer-run-parallel`
Running `composer ctal` [clear cache and run test-all]
- BEFORE: 30 sec
- AFTER: 20 sec
> Install composer-run-parallel (dev)

- CHANGELOG.md
- src/Framework/AbstractFactory.php
- src/Framework/ClassResolver/GlobalInstance/AnonymousGlobal.php
- src/Framework/Gacela.php
When using `resetInMemoryCache()` we should remove the internal cached state from Gacela; this is really useful for feature/integration tests. Eg:
```php
Gacela::bootstrap(__DIR__, static function (GacelaConfig $config): void {
$config->resetInMemoryCache();
});
```
- `ResetInMemoryCache` should work also from "anonymous globals" and "factory containers"
> ResetInMemoryCache also from anonymous globals and factory containers

- CHANGELOG.md
- src/Framework/Bootstrap/GacelaConfig.php
- tests/Benchmark/Framework/ClassResolver/FileCache/FileCacheBench.php
- tests/Feature/Framework/FileCache/FileCacheFeatureTest.php
- tests/Feature/Framework/ResolveDifferentProjectNamespaces/FeatureTest.php
- tests/Integration/Framework/Config/ConfigTest.php
- tests/Unit/Framework/Bootstrap/SetupGacelaTest.php
- tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
- Unify `setFileCacheEnabled` and `setFileCacheDirectory` into one single method: `setFileCache(bool $enabled, string $dir)`. Deprecated the former methods.
> Add GacelaConfig->setFileCache()

- CHANGELOG.md
- psalm.xml
- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Container/Locator.php
- src/Framework/Gacela.php
- src/Framework/Plugin/PluginInterface.php
- tests/Feature/Framework/PrePlugins/FeatureTest.php
- tests/Feature/Framework/PrePlugins/Module/Infrastructure/ExamplePlugin.php
There is no way to run custom code right after calling `Gacela::bootstrap()`. 
The goal is to allow running custom code that doesn't need to be define in the entry `index.php`, mainly to set a more complex custom configuration for the dedicated client app.
> Idea inspired by https://github.com/gacela-project/router/issues/25
- Create a `PluginInterface` which can be custom logic 
- And you can add your custom class in the `GacelaConfig::prePlugings()`
- Note: it has to extends that new `PluginInterface`
```php
Gacela::bootstrap(__DIR__, static function (GacelaConfig $config): void {
$config->prePlugins([
YourCustomLogicPlugin::class,
]);
});
```
>**Note**: The `YourCustomLogicPlugin` will be instantiated with the gacela container, which means we got auto-wiring for its …
> Allow running code right after bootstraping

- src/Framework/Container/Container.php
- src/Framework/Container/Locator.php
- src/Framework/Gacela.php
- tests/Unit/Framework/Container/LocatorTest.php
I discovered a bug while developing a `api-skeleton` repository, where I am using all gacela components together:
The reason was that after the change https://github.com/gacela-project/router/pull/28 we removed the three collaborator classes (via constructor) and instead we are passing an optional Clojure to the Router class. This, however, wasn't working fine with our current gacela container because it didn't know how to resolve those dependencies.
The solution was to allow defining external global bindings (currently known as `mappingInterfaces` at `GacelaConfig` level (extra: there is an issue to rename this concept to bindings https://github.com/gacela-project/gacela/issues/266 as done in the [gacela container project](https://github.com/gacela-project/container/blob/main/src/Containe …
> Use main container on plugins

- CHANGELOG.md
- composer.json
- src/Framework/Gacela.php
- src/Framework/Plugin/PluginInterface.php
- tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithConstructor.php
- tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithoutConstructor.php
The current `PluginInterface` forces you to implement that interface if you want to create a plugin, which forces you to require the entire gacela package as dependency.
However, it would be useful to allow any invokable/callable thing to be executed as a plugin, so you can define plugins that will be instantiated later without the need of depending on the fully gacela as dependency.
- Rename the `PluginInterface::run()` as just `PluginInterface::__invoke()`
> Rename PluginInterface main method

- CHANGELOG.md
- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupCombinator.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Gacela.php
- tests/Feature/Framework/Plugins/AfterFeatureTest.php
- tests/Unit/Framework/Bootstrap/SetupGacelaTest.php
Currently, we have only plugins that are executed right after bootstrapping gacela.
We want to add plugins before the bootstrapping, therefore the first step is to rename the "neutral plugins methods" to distinguish them between before and after.
- Rename `addPlugin()` to `addAfterPlugin()`
Add `GacelaConfig->addBeforePlugin()`
> Rename addPlugin() to addAfterPlugin()

- CHANGELOG.md
- src/Framework/Bootstrap/GacelaConfig.php
Remove from `GacelaConfig` the deprecated methods `setFileCacheEnabled()` and `setFileCacheDirectory()`.
> Remove deprecated setFileCacheEnabled() & setFileCacheDirectory()

- CHANGELOG.md
- src/Framework/Gacela.php
- tests/Integration/Framework/GacelaTest.php
I think it would be useful to be able to access to the rootDir of the application anywhere is needed, especially for configuration stuff.
>**Note** Thanks @JesusValera for the idea 💡 
- Save the appRootDir as static prop in the Gacela class and make it accesible from anywhere as static method.
> Add Gacela::rootDir()

- composer.json
- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Gacela.php
- tests/Feature/Framework/Plugins/FeatureTest.php
Currently, plugins are added by class names.
- Allow plugins as callables
```php
public function addPlugin(string|callable $plugin): self
```
> Allow plugins as callables

- composer.json
- src/Framework/Bootstrap/SetupCombinator.php
- src/Framework/Bootstrap/SetupEventDispatcher.php
- src/Framework/Bootstrap/SetupGacela.php
The current `SetupGacela` class is a bit overloaded. So we need to look for opportunities to extract logic from that class to make it easier to handle.
Scrutinizer score: https://scrutinizer-ci.com/g/gacela-project/gacela/code-structure/main/class/Gacela%5CFramework%5CBootstrap%5CSetupGacela
- Apply extract-class refactoring in the part where we are getting the event dispatcher from the `SetupGacela` creating a new class named `SetupEventDispatcher`
> Refactor setup event dispatcher

- src/Framework/Bootstrap/AbstractSetupGacela.php
- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- src/Framework/Config/GacelaConfigBuilder/AppConfigBuilder.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php
- src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php
- tests/Integration/Framework/Config/ConfigFactory/ConfigFactoryTest.php
- tests/Unit/Framework/Config/GacelaConfigBuilder/ConfigBuilderTest.php
- tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php
There is no change to the public API. The GacelaConfig has already `addAppConfig()`:
```php
function addAppConfig(string $path, string $pathLocal = '', $reader = null)
```
- Rename internal `ConfigBuilder` to `AppConfigBuilder` to avoid confusion
> Rename internal ConfigBuilder to AppConfigBuilder

- CHANGELOG.md
- src/Framework/Bootstrap/GacelaConfig.php
- src/Framework/Bootstrap/SetupCombinator.php
- src/Framework/Bootstrap/SetupGacela.php
- src/Framework/Bootstrap/SetupGacelaInterface.php
- tests/Feature/Framework/ExtendConfig/FeatureTest.php
Change `addExtendConfig()` to `extendGacelaConfig()`, eg:
```diff
-$config->addExtendConfig(BindingStringValue::class);
+$config->extendGacelaConfig(BindingStringValue::class);
```
> Rename method to extendGacelaConfig()

- .github/workflows/tests.yml
This pull request
💁‍♂️ `composer.lock` is currently not checked in, so there is no way to install locked dependencies.
- List individual changes in more detail
> Fix: Replace `locked` with `highest` in matrix

- tests/Feature/Console/CodeGenerator/MakeExceptionCommandTest.php
- tests/Feature/Console/CodeGenerator/MakeFileCommandTest.php
- tests/Feature/Console/CodeGenerator/MakeModuleCommandTest.php
- tests/Feature/Framework/FileCache/FileCacheFeatureTest.php
- tests/Feature/Framework/UsingAbstractGacelaClassesByDefault/FeatureTest.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverInMemoryAwareTest.php
It seems the when we write a path as follows `./something/else`, it doesn't work 100% on Windows.
In such case, let's replace the slash `/` by the PHP constant `DIRECTORY_SEPARATOR` which works in all OS.
> Replace / by DIRECTORY_SEPARATOR constant

- CHANGELOG.md
- src/Console/Infrastructure/Command/ListModulesCommand.php
- tests/Feature/Console/ListModules/ListModulesCommandTest.php
> Follow up after https://github.com/gacela-project/gacela/pull/293
- Add some color to the `gacela list:modules` command and improve its output
Project example used to run this command: https://github.com/phel-lang/phel-lang
> Color list modules command

- CHANGELOG.md
- src/Console/Infrastructure/Command/ListModulesCommand.php
- tests/Feature/Console/ListModules/ListModulesCommandTest.php
Original idea from @JesusValera.
- Use the detailed view of the command by default. Keep the simplified view (displaying only the module names) by using an optional option `--simple|-s`
> Use detailed by default instead of simple

- src/Framework/ClassResolver/DocBlockService/DocBlockServiceResolver.php
- tests/Integration/Framework/DocBlockResolver/DocBlockResolverTest.php
- tests/Integration/Framework/DocBlockResolver/Module/FakeCommand.php
- tests/Unit/Framework/ClassResolver/DependencyProvider/DependencyProviderNotFoundExceptionTest.php
- Add some tests for `DocBlockServiceNotFoundException` and `MissingClassDefinitionException`
> Add tests for DocBlockServiceNotFoundException

- phpstan.neon
- src/Framework/FactoryResolverAwareTrait.php
This condition is no longer needed and it was dead code 🥳 
- Remove method_exists(static::class, $name) to call parent::__call or __callStatic
> Simplify FactoryResolverAwareTrait

- src/Framework/Bootstrap/AbstractSetupGacela.php
- src/Framework/Bootstrap/Setup/GacelaConfigExtender.php
- src/Framework/Bootstrap/Setup/RunExtendConfig.php
- src/Framework/Bootstrap/SetupGacela.php
The aim is to reduce the complexity of `SetupGacela` class.
https://scrutinizer-ci.com/g/gacela-project/gacela/inspections/9d5d29e3-f35c-4175-81ee-55fc933a8a48/code-structure/class/Gacela%5CFramework%5CBootstrap%5CSetupGacela 
- Extract method `runExtendConfig()` to class `GacelaConfigExtender`
- Move constants from `SetupGacela` to `AbstractSetupGacela` class
> Refactor SetupGacela

- tests/Unit/Console/Domain/FileContent/FileContentGeneratorTest.php
The main logic for the file content generator was tested but not with the short name flag.
> Discovered thanks to mutation testing!
- Add tests for `FileContentGenerator` when using `withShortName: true`
> Test file content generator with short name

- src/Framework/Bootstrap/SetupGacela.php
- tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php
- Check that `areEventListenersEnabled` is actually true, and not just `not null`, because `false` would be also not a valid value
- Run `test_disable_class_resolver_listener` in a separate process to guarantee it is not affected by any other test - and avoid flackyness"
> Fix disable event listeners

- tests/Feature/Framework/StaticFacade/FeatureTest.php
The `tests/Feature/Framework/StaticFacade/FeatureTest.php` are flacky tests. Running them in isolation might help.
PHPUnit docs: https://docs.phpunit.de/en/11.3/annotations.html#preserveglobalstate
```php
#[RunInSeparateProcess]
#[PreserveGlobalState(false)]
```
> Fix flacky feature static facade tests

- CHANGELOG.md
- src/Framework/Config/Config.php
- tests/Feature/Framework/FileCache/FileCacheFeatureTest.php
Related: https://github.com/NixOS/nixpkgs/pull/314348#issuecomment-2509618056
> _A cache directory is being created in the Nix store which is immutable._
> _Is there a way to configure this cache directory with an environment variable or some other thing?_
This PR introduces an env variable that would override the full path of the cache dir where gacela cache files are stored.
- Added `GACELA_CACHE_DIR` env variable to override where to place the cache files
Using phel connected to my local gacela project with this PR changes to reproduce it and test it as well:
> Enable env var to define cache dir

- CHANGELOG.md
- tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php
- tests/Feature/Framework/StaticFacade/FeatureTest.php
- tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
- Better PHP 8.4 support
- Set new release version 1.9.1
> Better PHP 8.4 support

- CHANGELOG.md
- src/Framework/ClassResolver/Cache/AbstractPhpFileCache.php
- src/Framework/Config/PathFinder.php
- Added an internal cache to `PathFinder` to memoize glob results and skip repeated filesystem scans, improving loading performance
- Updated `AbstractPhpFileCache` to avoid rewriting unchanged cache files and to use `LOCK_EX` for safer writes
> Add internal cache on PathFinder
