tests/Fixtures/MissingConfigModule/MissingConfigModuleFacade.php, tests/Fixtures/MissingConfigModule/MissingConfigModuleFactory.php, tests/Fixtures/MissingFactoryModule/MissingFactoryModuleFacade.php, tests/Integration/IntegrationTest.php
Check exception error when calling in a module the:
1. factory
2. config
What do you think, are those tests worthful? 😄
=> Add tests missing factory & config

src/ClassResolver/AbstractClassResolver.php
Clean the `AbstractClassResolver`.
I also check the other project class and seems fine. 😄 
- Rearrange class
- Remove useless methods (`findCacheKey()`, `resolveClassName ()`)
- Return `void` on `setCallerObject()`
- `getCacheKey()` L26 returns `string`, remove the `$cacheKey !== null` condition on L28 & L32
=> Clean-up AbstractClassResolver

documentation/001_basic_concepts.md, documentation/002_facade.md, documentation/003_factory.md, documentation/004_dependency_provider.md, documentation/005_config.md
Just some minor improvements on the docs.
No relevant changes :)
=> improves docs

src/Container/Container.php, src/Container/Locator.php, tests/Fixtures/ExampleA/ExampleAFacade.php, tests/Fixtures/ExampleA/ExampleAFacadeInterface.php, tests/Fixtures/ExampleB/ExampleBDependencyProvider.php, tests/Fixtures/ExampleB/ExampleBFacade.php, tests/Fixtures/ExampleB/ExampleBFacadeInterface.php, tests/Fixtures/ExampleC/ExampleCDependencyProvider.php, tests/Fixtures/MissingConfigModule/MissingConfigModuleFacade.php, tests/Fixtures/MissingConfigModule/MissingConfigModuleFactory.php
The Locator will avoid creating a new instance of each Facade. They will be reused as singletons via all different modules which use the Container->getLocator() in their DependecyProvider.
- Add a Locator inside the Container.
=> Implementing a Locator to get the Facades from the DependencyProvider

src/ClassResolver/ClassNameFinder/ClassNameFinder.php, src/ClassResolver/ClassNameFinder/Rule/FinderRuleInterface.php, src/ClassResolver/ClassNameFinder/Rule/FinderRuleWithModulePrefix.php, src/ClassResolver/ClassNameFinder/Rule/FinderRuleWithoutModulePrefix.php, src/ClassResolver/ClassResolverFactory.php
- Refactor ClassNameFinder; extract methods to classes and create FinderRuleInterface
=> Create FinderRuleInterface to be used in the ClassNameFinder

.php_cs.dist, src/AbstractFactory.php, src/AbstractRepository.php, src/ClassResolver/ClassResolverExceptionTrait.php, src/ClassResolver/Config/ConfigNotFoundException.php, src/ClassResolver/DependencyProvider/DependencyProviderNotFoundException.php, src/ClassResolver/Factory/FactoryNotFoundException.php, src/ClassResolver/Repository/RepositoryNotFoundException.php, src/ClassResolver/Repository/RepositoryResolver.php, src/RepositoryResolverAwareTrait.php, tests/Fixtures/ExampleC/ExampleCFactory.php, tests/Fixtures/ExampleC/ExampleCRepository.php, tests/Fixtures/ExampleC/ExampleCRepositoryInterface.php, tests/Fixtures/ExampleC/Service/ServiceC.php, tests/Integration/IntegrationTest.php
- Adding getRepository() to a Factory
=> Adding repository to factory

README.md, docs/004_config.md
Using config directory instead of a config.php at the root of the project
=> Update config documentation

LICENSE, README.md
Add MIT license to the project
- Create `LICENSE` file
- Update `README.md` with the badge
=> Add LICENSE to the project

src/CodeGenerator/Domain/FilenameSanitizer.php, src/CodeGenerator/Infrastructure/Command/MakeFileCommand.php, tests/Unit/CodeGenerator/Domain/FilenameSanitizerTest.php
- Accept multiple filenames when using `make:file` command
=> MakeFileCommand accept multiple filenames

.github/workflows/ci.yml, composer.json, composer.lock, phpstan.neon
- Added as require --dev the latest PHPStan with level 5
=> Install phpstan level 5

src/CodeGenerator/CodeGeneratorFactory.php, src/CodeGenerator/Domain/FileContentGenerator.php, src/CodeGenerator/Infrastructure/FileContentIo.php, src/CodeGenerator/Infrastructure/FileContentIoInterface.php, tests/Unit/CodeGenerator/Domain/CommandArgumentsParserTest.php, tests/Unit/CodeGenerator/Domain/FileContentGeneratorTest.php, tests/Unit/CodeGenerator/Domain/FilenameSanitizerTest.php
- Create tests FileContentGenerator
- Add missing tests for FilenameSanitizer & CommandArgumentsParser
=> Add tests for CodeGenerator Domain layer

src/Framework/ClassResolver/AbstractClassResolver.php, src/Framework/ClassResolver/ClassResolverExceptionTrait.php, src/Framework/ClassResolver/Config/ConfigNotFoundException.php, src/Framework/ClassResolver/Config/ConfigResolver.php, src/Framework/ClassResolver/DependencyProvider/DependencyProviderNotFoundException.php, src/Framework/ClassResolver/DependencyProvider/DependencyProviderResolver.php, src/Framework/ClassResolver/Factory/FactoryNotFoundException.php, src/Framework/ClassResolver/Factory/FactoryResolver.php
- Remove classInfo as property from AbstractClassResolver
=> AbstractClassResolver refactoring

src/Framework/Container/Locator.php, tests/Fixtures/StringValue.php, tests/Fixtures/StringValueInterface.php, tests/Unit/Framework/Container/ContainerTest.php, tests/Unit/Framework/Container/LocatorTest.php
- Add unit tests to the Container and Locator classes
=> Adding unit tests to Container and Locator

.gitignore, composer.json, composer.lock, phpbench.json, src/Framework/ClassResolver/AbstractClassResolver.php, src/Framework/ClassResolver/ClassInfo.php, tests/Benchmark/Framework/ClassResolver/AbstractFacadeBench.php, tests/Integration/Framework/GlobalServices/GlobalServicesTest.php
https://github.com/gacela-project/gacela/issues/31
=> Add phpbench dependency

CHANGELOG.md, src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php, src/Framework/ClassResolver/DependencyResolver/DependencyResolverNotFoundException.php, src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php, tests/Integration/Framework/UsingConfigInterfacesMapping/IntegrationTest.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/NumberService.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvedClassInterface.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAbstractAnonClassCallable.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAbstractAnonClassFunction.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAnonClassCallableInterface.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Domain/ResolvingAnonClassFunctionInterface.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Facade.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Factory.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/CorrectCompanyGenerator.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/CustomResolvedClass.php, tests/Integration/Framework/UsingConfigInterfacesMapping/LocalConfig/Infrastructure/IncorrectCompanyGenerator.php, tests/Integration/Framework/UsingConfigInterfacesMapping/gacela.php, tests/Integration/Framework/UsingDeprecatedArrayConfig/LocalConfig/Factory.php
The `DependencyResolver` class now is smarter.
Add a lot of tests to check the resolver works as expected (_probably we should work on the class-naming in a future iteration_).
=> Some edge-cases in DependencyResolver

phpstan.neon, src/Framework/AbstractConfigGacela.php, src/Framework/ClassResolver/AbstractClassResolver.php, src/Framework/ClassResolver/ClassInfo.php, src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php, src/Framework/Config.php, src/Framework/Config/ConfigInit.php, src/Framework/Config/ConfigReader/EnvConfigReader.php, src/Framework/Config/ConfigReader/PhpConfigReader.php, src/Framework/Config/ConfigReaderInterface.php, src/Framework/Config/GacelaConfigFileFactory.php, src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php, src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php, src/Framework/Config/PathFinder.php, src/Framework/Config/PathFinderInterface.php, src/Framework/Exception/Backtrace.php
Increate `PhpStan` from level 5 to 8.
=> Increase PhpStan to max level

composer.json, composer.lock, phpstan.neon, src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php, src/Framework/Config/GacelaFileConfig/GacelaConfigItem.php, src/Framework/Exception/Backtrace.php
Update PHPStan to 1.0 & fix issues
=> Update PHPStan to 1.0 & fix issues

composer.json, composer.lock, phpstan.neon, src/CodeGenerator/CodeGeneratorConfig.php, src/CodeGenerator/Domain/CommandArguments/CommandArgumentsParser.php, src/CodeGenerator/Infrastructure/Command/MakeFileCommand.php
=> Update PHPStan to 1.0

tests/Feature/CodeGenerator/MakeFileCommandTest.php, tests/Feature/CodeGenerator/MakeModuleCommandTest.php
- Move to setUp() and tearDownAfterClass() the remove temp test directory
=> Refactor CodeGenerator feature tests.

composer.json
Add `homepage` section in `composer.json` file.
=> Add homepage to composer.json

src/Framework/AbstractConfigGacela.php, src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php, src/Framework/ClassResolver/CustomService/CustomServiceNotValidException.php, src/Framework/ClassResolver/CustomService/CustomServiceResolver.php, tests/Feature/Framework/CustomServices/CustomModule/Application/Greeter.php, tests/Feature/Framework/CustomServices/CustomModule/Facade.php, tests/Feature/Framework/CustomServices/CustomModule/Factory.php, tests/Feature/Framework/CustomServices/CustomModule/Infrastructure/Persistence/EntityManager.php, tests/Feature/Framework/CustomServices/CustomModule/Infrastructure/Persistence/Repository.php, tests/Feature/Framework/CustomServices/FeatureTest.php
Add documentation with some examples in the `AbstractConfigGacela` class.
=> Add documentation to AbstractConfigGacela class

composer.lock, src/Framework/AbstractConfig.php
Allow easy access the root dir of the project from the Factory.
Changes getAppRootDir() method to 'public'
=> Make public getAppRootDir() #115

.php-cs-fixer.dist.php, composer.json, composer.lock, phpbench.json, src/Framework/ClassResolver/AbstractClassResolver.php, src/Framework/ClassResolver/ClassInfo.php, src/Framework/ClassResolver/Config/ConfigResolver.php, src/Framework/ClassResolver/DependencyProvider/DependencyProviderResolver.php, src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php, src/Framework/ClassResolver/Factory/FactoryResolver.php, src/Framework/ClassResolver/InstanceCreator/InstanceCreator.php, src/Framework/ClassResolver/ResolvableType.php, src/Framework/Config.php, src/Framework/Config/ConfigReader/PhpConfigReader.php, src/Framework/Config/PathNormalizer/WithSuffixAbsolutePathStrategy.php, src/Framework/ConfigResolverAwareTrait.php, src/Framework/Container/Locator.php, src/Framework/FactoryResolverAwareTrait.php, tests/Benchmark/Framework/ClassResolver/AnonymousGlobal/AnonymousGlobalsBench.php, tests/Benchmark/Framework/ClassResolver/ClassInfo/ClassInfoBench.php, tests/Benchmark/Framework/ClassResolver/NormalModule/NormalModuleBench.php, tests/Feature/Framework/BindingInterfacesWithInnerDependencies/gacela.php, tests/Fixtures/SimpleEnvConfigReader.php
- Composer update phpstan to latest 1.5
- Use PHPBench revs & iterations from phpbench.json config file
- Disable yoda style
=> Update php cs rules

src/Framework/ClassResolver/DependencyResolver/DependencyResolver.php
Simplify the `DependencyResolver->resolveDependenciesRecursively()` into multiple methods, additionally, reached the level 10 in Scrutinizer 🎉
=> Split resolveDependenciesRecursively() into multiple methods

src/Framework/Bootstrap/GacelaConfig.php, tests/Feature/Framework/AnonymousGlobalExtendsExistingClass/FeatureTest.php, tests/Feature/Framework/AnonymousGlobalExtendsExistingClass/Module/Config.php, tests/Feature/Framework/AnonymousGlobalExtendsExistingClass/Module/Facade.php, tests/Feature/Framework/AnonymousGlobalExtendsExistingClass/Module/Factory.php, tests/Feature/Framework/AnonymousGlobalExtendsExistingClass/config/default.php, tests/Feature/Framework/DocBlockServiceAware/config/default.php, tests/Feature/Framework/FacadeAware/config/default.php
- Added `GacelaConfig::withPhpConfigDefault()`
- Created a feature `test_override_existing_resolved_class_when_config_method_is_called`
=> Add GacelaConfig::withPhpConfigDefault()

composer.lock, src/Framework/Bootstrap/SetupGacela.php
The last version of PHPStan gave me some feedback with an idea to refactor the SetupGacela class.
- Upgrade PHPStan and refactor SetupGacela
=> Refactor SetupGacela

.editorconfig, .gitattributes, README.md
Add `.editorconfig` and  `.gitattributes` in order to omit the selected files when someone pulls the project.
=> Add .editorconfig & .gitattributes files

composer.json, psalm.xml
- Add `psalm/plugin-phpunit` dependency
- Sort alphabetically and update dependencies
=> Add "psalm/plugin-phpunit" + update dependencies

CHANGELOG.md, src/Console/ConsoleDependencyProvider.php, src/Console/ConsoleFacade.php, src/Console/ConsoleFactory.php, src/Console/Domain/Cache/CacheClearer.php, src/Console/Domain/Cache/DirectoryIoInterface.php, src/Console/Infrastructure/Command/ClearCacheCommand.php, src/Console/Infrastructure/DirectoryIo.php, src/Framework/AbstractConfig.php
Issue: https://github.com/gacela-project/gacela/issues/192
- Create `ClearCacheCommand` 
Example:
=> Create gacela cache:clear command

src/Framework/ClassResolver/Cache/ClassNameCacheInterface.php, src/Framework/ClassResolver/Cache/InMemoryClassNameCache.php, src/Framework/ClassResolver/Cache/ProfiledInMemoryCache.php, src/Framework/ClassResolver/ClassNameFinder/ClassNameFinder.php, src/Framework/ClassResolver/ClassResolverFactory.php, src/Framework/ClassResolver/Profiler/AbstractJsonFileProfiler.php, src/Framework/ClassResolver/Profiler/ClassNameJsonProfiler.php, src/Framework/ClassResolver/Profiler/CustomServicesJsonProfiler.php, src/Framework/ClassResolver/Profiler/FileProfilerInterface.php, src/Framework/DocBlockResolver/DocBlockResolver.php, src/Framework/Gacela.php, tests/Benchmark/Framework/ClassResolver/FileProfiler/FileProfilerBench.php, tests/Feature/Framework/CustomNoCacheDirectory/NoFileCacheFeatureTest.php, tests/Feature/Framework/CustomProfilerDirectory/FileProfilerFeatureTest.php, tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php, tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverInMemoryAwareTest.php, tests/Unit/Framework/ClassResolver/ClassNameFinderTest.php
Minor refactoring grouping the Cache and Profiler classes inside their proper directories inside ClassResolver.
=> Group Cache and Profiler classes inside their folders

src/Framework/Bootstrap/AbstractSetupGacela.php, src/Framework/Bootstrap/GacelaConfig.php, src/Framework/Bootstrap/SetupGacela.php, src/Framework/Bootstrap/SetupGacelaInterface.php
Add PHPdoc to `GacelaConfig` and `SetupGacelaInterface` classes to improve user experience 👍🏼
=> Add documentation to GacelaConfig & SetupGacelaInterface classes

src/Framework/ClassResolver/ClassResolverFactory.php, src/Framework/EventListener/ClassResolver/Cache/ClassNamePhpCacheCreatedEvent.php, src/Framework/EventListener/ClassResolver/Cache/InMemoryCacheCreatedEvent.php, tests/Feature/Framework/ListeningEvents/ClassResolver/DisableListenersTest.php, tests/Feature/Framework/ListeningEvents/ClassResolver/GacelaClassResolverGeneralListenerTest.php, tests/Integration/Framework/GlobalServices/AnonymousClassesTest.php
- Add `ClassNamePhpCacheCreatedEvent`
- Add `InMemoryCacheCreatedEvent`
=> Added File and InMemory *CacheCreatedEvent

src/Framework/ClassResolver/AbstractClassResolver.php, src/Framework/ClassResolver/ClassResolverFactory.php, src/Framework/Config/ConfigReader/PhpConfigReader.php, src/Framework/Event/Dispatcher/EventDispatchingCapabilities.php
In every place where we want to dispatch events we are repeating the same code.
- Create a trait `EventDispatchingCapabilities` which has the method `dispatchEvent()` so it will simplify the way how to dispatch events.
=> Refactor dispatchEvent into EventDispatchingCapabilities trait

src/Framework/Container/Container.php
The `$raw` array from `Container` is not necessary, removed 😄
=> Remove $raw array from container

.editorconfig, .github/workflows/ci.yml
- Trigger the CI not on pull_request and on push, but only on pull_request
- Trigger the CI on push only for master branch
- Add matrix.dependencies
> Inspired by https://github.com/DaveLiddament/sarb/blob/master/.github/workflows/full-checks.yml#L17-L67
=> Trigger the CI on push only for master branch

composer.json, src/Console/Domain/FilenameSanitizer/FilenameSanitizer.php, src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php
Psalm 5 was just released! https://psalm.dev/articles/psalm-5
- Upgrade psalm to `^5.1`
=> Update psalm 5

.github/workflows/ci.yml
- Ensure Gacela is compatible with PHP 8.2
=> Add PHP 8.2 to CI

src/Framework/Bootstrap/SetupCombinator.php, src/Framework/Bootstrap/SetupCombiner.php, src/Framework/Bootstrap/SetupGacela.php
The `SetupGacela` was getting too big and getting the worst qualification in `Scrutinizer`.
=> Extract combiner logic from SetupGacela

CHANGELOG.md, phpstan.neon, psalm.xml, src/Framework/FactoryResolverAwareTrait.php, tests/Feature/Framework/StaticFacade/FeatureTest.php, tests/Feature/Framework/StaticFacade/Module/Config.php, tests/Feature/Framework/StaticFacade/Module/Domain/FormalGreeter.php, tests/Feature/Framework/StaticFacade/Module/Domain/GreeterInterface.php, tests/Feature/Framework/StaticFacade/Module/Domain/InformalGreeter.php, tests/Feature/Framework/StaticFacade/Module/Facade.php, tests/Feature/Framework/StaticFacade/Module/Factory.php
Allow using static method from your Facade directly.
=> Allow using static facade

CHANGELOG.md, src/Framework/ConfigResolverAwareTrait.php, tests/Feature/Framework/StaticFacade/FeatureTest.php, tests/Feature/Framework/StaticFacade/Module/Facade.php, tests/Feature/Framework/StaticFacade/Module/Factory.php
Inspired by https://github.com/gacela-project/gacela/pull/251 
- Allow using static `::config()` from any Factory
=> Allow using ::config() from any Factory

src/Framework/Bootstrap/AbstractSetupGacela.php, src/Framework/Bootstrap/SetupGacela.php, src/Framework/Bootstrap/SetupGacelaInterface.php
- SetupGacela uses AbstractSetupGacela parent methods
=> Use AbstractSetupGacela parent methods

CHANGELOG.md, composer.json, src/Framework/ClassResolver/AbstractClassResolver.php
- Use `gacela-project/container` instead of `gacela-project/resolver`
=> Use container instead of resolver dependency

src/Framework/Bootstrap/SetupCombinator.php, src/Framework/Bootstrap/SetupGacela.php, src/Framework/Container/Container.php, src/Framework/Container/ContainerInterface.php, src/Framework/Container/Locator.php, src/Framework/Container/LocatorInterface.php, tests/Feature/Framework/Plugins/FeatureTest.php, tests/Unit/Framework/Bootstrap/SetupGacelaTest.php
- Add plugins when combining different setups
=> Combine plugins

CHANGELOG.md, src/Framework/Bootstrap/AbstractSetupGacela.php, src/Framework/Bootstrap/GacelaConfig.php, src/Framework/Bootstrap/SetupGacela.php, src/Framework/Bootstrap/SetupGacelaInterface.php, src/Framework/ClassResolver/AbstractClassResolver.php, src/Framework/Config/GacelaConfigBuilder/BindingsBuilder.php, src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactory.php, src/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactory.php, src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php, src/Framework/Config/GacelaFileConfig/GacelaConfigFileInterface.php, src/Framework/Container/Container.php, tests/Benchmark/Framework/ClassResolver/FileCache/FileCacheBench.php, tests/Feature/Framework/BindingInterfacesInGacelaConfigFile/gacela.php, tests/Feature/Framework/BindingInterfacesWithInnerDependencies/gacela.php, tests/Integration/Framework/Config/ConfigFactory/ConfigFactoryTest.php, tests/Integration/Framework/Config/ConfigFactory/WithGacelaFile/gacela.php, tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigFromBootstrapFactoryTest.php, tests/Unit/Framework/Config/GacelaFileConfig/Factory/GacelaConfigUsingGacelaPhpFileFactoryTest.php, tests/Unit/Framework/Config/GacelaFileConfig/GacelaConfigFileTest.php
Issue: https://github.com/gacela-project/gacela/issues/266 
- Rename mappingInterfaces to bindings
=> Rename mapping to bindings

src/Framework/Bootstrap/GacelaConfig.php, tests/Feature/Framework/FileCache/FileCacheFeatureTest.php
- Add GacelaConfig::enableFileCache()
=> Add GacelaConfig::enableFileCache()

tests/Feature/Framework/Plugins/FeatureTest.php, tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithConstructor.php, tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithInvokeArgs.php, tests/Feature/Framework/Plugins/Module/Infrastructure/ExamplePluginWithoutConstructor.php
Add one more feature test to verify that a plugin class resolves its invoke arguments automatically, the same way as they are resolved in the class constructor.
=> Test autoload plugin invoke args

phpstan.neon, src/Console/ConsoleFacade.php, src/Console/Domain/AllAppModules/AllAppModulesFinder.php, src/Console/Infrastructure/Command/ListModulesCommand.php, tests/Feature/Console/ListModules/FilterListModulesCommandTest.php, tests/Feature/Console/ListModules/ListModulesCommandTest.php, tests/Integration/Console/AllAppModules/Domain/AllAppModulesFinderTest.php
Add the `filter` argument to `gacela list:module` command:
=> Filter list modules command

.github/workflows/tests.yml
This pull request
💁‍♂️ Also see workflow and step identifier proposed in #270.
- List individual changes in more detail
=> Fix: Adjust identifier

.github/workflows/tests.yml, .gitignore, composer.lock
This pull request
- List individual changes in more detail
=> Fix: Check in `composer.lock`

.github/workflows/mutation-testing.yml, .gitignore, README.md, composer.json, composer.lock, infection.json5
Simila as we did on container and router, we want to install and get the benefits from infection php mutation testing framework on the core repository of gacela.
- install infection
=> Install infection

CHANGELOG.md, src/Console/Domain/AllAppModules/AppModule.php, src/Console/Domain/AllAppModules/AppModuleCreator.php, src/Console/Infrastructure/Command/ListModulesCommand.php, tests/Feature/Console/ListModules/ListModulesCommandTest.php, tests/Integration/Console/AllAppModules/Domain/AllAppModulesFinderTest.php
Change design from the simple view:
to the following table:
=> Change design simple view from gacela list:modules

composer.json
This pull request
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.
=> Enhancement: Keep packages sorted in `composer.json`

.github/workflows/code-style.yml, composer.json, composer.lock
=> Enhancement: Require and use `ergebnis/composer-normalize`

composer.json, composer.lock, phpstan.neon, src/Console/Domain/AllAppModules/AllAppModulesFinder.php, src/Console/Domain/FileContent/FileContentGenerator.php, src/Console/Infrastructure/Command/ListModulesCommand.php, src/Framework/Bootstrap/SetupGacela.php, src/Framework/ClassResolver/Cache/AbstractPhpFileCache.php, src/Framework/ClassResolver/Cache/CacheInterface.php, src/Framework/ClassResolver/Cache/InMemoryCache.php, src/Framework/ClassResolver/DocBlockService/DocBlockParser.php, src/Framework/ClassResolver/DocBlockService/UseBlockParser.php, src/Framework/ClassResolver/GlobalInstance/AnonymousGlobal.php, src/Framework/Config/GacelaFileConfig/GacelaConfigFile.php, src/Framework/Container/Locator.php, src/Framework/DocBlockResolverAwareTrait.php, src/Framework/FactoryResolverAwareTrait.php
On top of PHPStan max level...
- Add `phpstan/phpstan-strict-rules`
- Enable `bleedingEdge` PHPStan rules
> Implementing what I have learned from here https://youtu.be/AFjr3RlDOZQ by @ondrejmirtes
=> Install phpstan strict rules

src/Framework/ClassResolver/Cache/GacelaFileCache.php, src/Framework/Config/Config.php
Related: https://github.com/NixOS/nixpkgs/pull/314348#issuecomment-2509725573
=> Use sys_get_temp_dir as DefaultCacheDir

.github/workflows/code-style.yml, .github/workflows/tests.yml, CHANGELOG.md, src/Framework/ClassResolver/GlobalInstance/AnonymousGlobal.php, src/Framework/Gacela.php, tests/Unit/Framework/Gacela/AddGlobalContextTest.php
- improve internals for Gacela::addGlobal
- cover with unit test
=> Improve internal addGlobal

CHANGELOG.md, src/Framework/Config/Config.php, tests/Integration/Framework/DocBlockResolverAware/DocBlockResolverCustomServicesAwareTest.php
- Fix `getDefaultCacheDir` and `DocBlockResolverCustomServicesAwareTest`
=> Fix default cache dir

CHANGELOG.md, docs/getting-started.md, src/Console/Infrastructure/Command/ListModulesCommand.php, src/Framework/AbstractFactory.php, tests/Feature/Console/ListModules/ListModulesCommandTest.php, tests/Unit/Framework/Factory/FactorySingletonTest.php
Sometimes we might want to create a singleton from our Factories, instead of creating a new instance all the time.
- Enable creating a singleton from a Factory
=> Add singleton to Factory
